/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.colibria.android.sipservice;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int icon=0x7f020000;
    }
    public static final class id {
        public static final int prefConferenceFacUri=0x7f050005;
        public static final int prefDisplayName=0x7f050002;
        public static final int prefEnableService=0x7f050000;
        public static final int prefPassword=0x7f050007;
        public static final int prefServiceStatus=0x7f050001;
        public static final int prefSipProxyHost=0x7f050008;
        public static final int prefSipProxyPort=0x7f050009;
        public static final int prefSipUri=0x7f050003;
        public static final int prefTelUri=0x7f050004;
        public static final int prefUsername=0x7f050006;
        public static final int prefVersion=0x7f05000a;
    }
    public static final class layout {
        public static final int preferences=0x7f030000;
    }
    public static final class string {
        public static final int app_name=0x7f040000;
        public static final int config_invalid_auth_password=0x7f040011;
        public static final int config_invalid_auth_username=0x7f040010;
        public static final int config_invalid_conf_fac=0x7f04000d;
        public static final int config_invalid_display_name=0x7f04000a;
        public static final int config_invalid_proxy_host=0x7f04000e;
        public static final int config_invalid_proxy_port=0x7f04000f;
        public static final int config_invalid_sip_uri=0x7f04000b;
        public static final int config_invalid_tel_uri=0x7f04000c;
        public static final int presence_status_disabled=0x7f040007;
        public static final int presence_status_subscribed=0x7f040009;
        public static final int presence_status_subscribing=0x7f040008;
        public static final int service_status_connected=0x7f040005;
        public static final int service_status_connecting=0x7f040004;
        public static final int service_status_disabled=0x7f040003;
        public static final int service_status_registered=0x7f040006;
        public static final int service_status_unconfigured=0x7f040001;
        public static final int service_status_unconfigured_error=0x7f040002;
    }
}
